Loading dbcore fails on windows
Araneidae/epicsdbbuilder pull request #5
Opened 2020-09-10 11:45 UTC by hanak

**Problem**
Using package on Windows (Windows 10) fails on loading dbCode library even though the library is built and available at the path (including its dependencies).

**Analysis**
The Python code assumes Linux environment in names of shared libraries and paths.

**Fix**
* Use correct Windows shared library names and path separators if Python detects Windows.
* Allow "EPICS_HOST_ARCH" environment variable in `examples/test.py`. This enables use of cross-compiled MingW binaries with no modifications `examples/test.py`.
* Use file output on Windows because `/dev/stdout` is not available on Windows.

**Testing**
* Run `python examples/test.py` on Windows 10 (32-bit binaries built with MingW)
* Run `python examples/test.py` on Debian 10  (64-bit binaries)

2020-09-10 12:25 UTC, Araneidae requested changes
Thank you for this pull request.  I had no idea that epicsdbbuilder would actually work on Windows!

This looks like a clean patch, but can you please add a further commit to fix the trivial layout issues, and then I'll happily pull.

2020-09-10 12:25 UTC, Araneidae commented on epicsdbbuilder/dbd.py
> +        ctypes.byref(_db), filename, separator.join(['.', os.path.join(_epics_base, 'dbd')]), None)
Please split this line to fit within 80 columns.  I suggest splitting after `filename,` and aligning `separator` with `ctypes` on the line above.

2020-09-10 12:25 UTC, Araneidae commented on epicsdbbuilder/mydbstatic.py
> +            epics_base, library_location, host_arch, library_name_format.format('dbCore')))
Same as before: please split this line and line 82 below to fit in 80 columns.  Split after `host_arch,` and align with `epics_base,`.

2020-09-10 12:25 UTC, Araneidae commented on examples/.gitignore
> +test_output.db
There's a missing newline at the end of this file, please do add.

2020-09-11 07:00 UTC, hanak commented
Thank you for the review. I have updated the code accordingly.

2020-09-11 07:03 UTC, merged

2020-09-11 07:03 UTC, Araneidae commented
Thank you for this change.